databaseUrl=${SPRING_DATA_MONGODB_URI}
databaseName=ead_ca2
databaseCollection=ead_2024

management.endpoints.web.exposure.include=env,health
management.endpoint.health.show-details=always

management.server.port=8080

org.springframework.web.servlet.mvc.method.annotation=DEBUG
log4j.logger.org.springframework.web.servlet.mvc.method.annotation=DEBUG, console
logging.level.org.springframework.web= DEBUG
spring.http.log-request-details=true
