apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: seshukalakurthi/eadca2_frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: WEB_SERVICE_HOST
          value: backend
        - name: WEB_SERVICE_PORT
          value: "8080"
