name: ACR CI
# Pushing Images to Azure Contanier Registry

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Check Azure Account
        run: az account show

      # Backend
      - name: Build Backend Image
        run: |
          docker build -t eadeployca2registry.azurecr.io/eadca2_backend:latest ./EAD_BE_CA2

      # Frontend
      - name: Build Frontend Image
        run: |
          docker build -t eadeployca2registry.azurecr.io/eadca2_frontend:latest ./EAD_FE_CA2

      - name: Push Backend Image
        run: |
          docker push eadeployca2registry.azurecr.io/eadca2_backend:latest

      - name: Push Frontend Image
        run: |
          docker push eadeployca2registry.azurecr.io/eadca2_frontend:latest
