name: ACR CI-CD
# Pushing Images to ACR & Running Pods in AKS

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: az acr login --name eadeployca2receiperegistry

      - name: Check Azure Account
        run: az account show

      # Backend
      - name: Build Backend Image
        run: |
          docker build -t eadeployca2receiperegistry.azurecr.io/eadca2_backend:latest ./EAD_BE_CA2

      # Frontend
      - name: Build Frontend Image
        run: |
          docker build -t eadeployca2receiperegistry.azurecr.io/eadca2_frontend:latest ./EAD_FE_CA2

      - name: Push Backend Image
        run: |
          docker push eadeployca2receiperegistry.azurecr.io/eadca2_backend:latest

      - name: Push Frontend Image
        run: |
          docker push eadeployca2receiperegistry.azurecr.io/eadca2_frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-and-push
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    
      - name: Get AKS Credentials
        run: |
          az aks get-credentials \
            --resource-group ${{ secrets.RESOURCE_GROUP}} \
            --name ${{ secrets.AKS_CLUSTER }} \
            --overwrite-existing

      - name: Create MongoDB Secret in AKS
        run: |
          kubectl create secret generic mongodb-secret \
          --from-literal=MONGO_URI="${{ secrets.MONGO_URI }}" \
          --from-literal=username=eac2024 \
          --from-literal=password=eac2024 \
          --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy to AKS
        run: |
          kubectl apply -f k8s/backend/
          kubectl apply -f k8s/frontend/
          kubectl apply -f k8s/mongodb/

      - name: Verify Deployment
        run: |
          kubectl get all
