name: ACR CI
# Pushing Images to ACR

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
         
      - name: Set image tag
        run: echo "IMAGE_TAG=${{ github.run_number }}" >> $GITHUB_ENV

      - name: Upload tag artifact
        uses: actions/upload-artifact@v4
        with:
          name: image-tag
          path: image_tag.txt

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: az acr login --name eadeployca2receiperegistry

      - name: Check Azure Account
        run: az account show

      # Install Trivy
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      # Backend
      - name: Build Backend Image
        run: |
          docker build -t eadeployca2receiperegistry.azurecr.io/eadca2_backend:${IMAGE_TAG} ./EAD_BE_CA2

      # Frontend
      - name: Build Frontend Image
        run: |
          docker build -t eadeployca2receiperegistry.azurecr.io/eadca2_frontend:${IMAGE_TAG} ./EAD_FE_CA2

      # Scan Backend Image
      - name: Scan Backend Image
        run: |
          trivy image --exit-code 0 --severity HIGH,CRITICAL \
          eadeployca2receiperegistry.azurecr.io/eadca2_backend:${IMAGE_TAG}

      # Scan Frontend Image
      - name: Scan Frontend Image
        run: |
          trivy image --exit-code 0 --severity HIGH,CRITICAL \
          eadeployca2receiperegistry.azurecr.io/eadca2_frontend:${IMAGE_TAG}

      - name: Push Backend Image
        run: |
          docker push eadeployca2receiperegistry.azurecr.io/eadca2_backend:${IMAGE_TAG}

      - name: Push Frontend Image
        run: |
          docker push eadeployca2receiperegistry.azurecr.io/eadca2_frontend:${IMAGE_TAG}
