name: Staging CD with k6 & zap Test

on:
   workflow_dispatch:
  

jobs:
  load-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Install k6
      - name: Install k6
        run: |
          sudo apt-get update
          sudo apt-get install -y gnupg ca-certificates
          curl https://dl.k6.io/key.gpg | sudo gpg --yes --dearmor -o /usr/share/keyrings/k6-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install -y k6]
          
      # Run k6
      - name: Run k6 Performance Tests
        env:
          BASE_URL: ${{ vars.BASE_URL }}
        run: |
          k6 run perf-tests-k6/bp-bmi-loadtest.js | tee k6report.txt

      - name: Upload k6 Report
        uses: actions/upload-artifact@v4
        with:
          name: k6-performance-report
          path: k6report.txt
